In [ ]:
#Question 4 - Movies data

In [61]:
#Importing libraries and reading csv
import pandas as pd
import numpy as np
import re
df=pd.read_csv('Data/movies_awards.csv',sep=',')[['Title','Awards']]

In [65]:


#Getting the number of awards and nominations using regex patterns


df['Wins'] = df['Awards'].str.extract('(\d+) w', expand=True).fillna(0)
df['Nominations']  = df['Awards'].str.extract('(\d+) n', expand=True).fillna(0)
df['Bafta_Nominations']  = df['Awards'].str.extract('Nominated for (\d+) BAFT', expand=True).fillna(0)
df['Oscar_Nominations']  = df['Awards'].str.extract('Nominated for (\d+) Oscar', expand=True).fillna(0)
df['Prime_Nominations'] = df['Awards'].str.extract('Nominated for (\d+) Prime', expand=True).fillna(0)
df['Golden_Globe_Nominations'] = df['Awards'].str.extract('Nominated for (\d+) Golden', expand=True).fillna(0)
df['Bafta_Wins']  = df['Awards'].str.extract('Won (\d+) BAFTA', expand=True).fillna(0)
df['Oscar_Wins']  = df['Awards'].str.extract('Won (\d+) Oscar[s]?', expand=True).fillna(0)
df['Prime_Wins'] = df['Awards'].str.extract('Won (\d+) Prime', expand=True).fillna(0)
df['Golden_Globe_Wins'] = df['Awards'].str.extract('Won (\d+) Golden', expand=True).fillna(0)


df[['Wins','Nominations']]=df[['Wins','Nominations']].apply(pd.to_numeric,errors='ignore')
df[['Bafta_Nominations']]=df[['Bafta_Nominations']].apply(pd.to_numeric,errors='ignore')
df[['Oscar_Nominations']]=df[['Oscar_Nominations']].apply(pd.to_numeric,errors='ignore')
df[['Prime_Nominations']]=df[['Prime_Nominations']].apply(pd.to_numeric,errors='ignore')
df[['Golden_Globe_Nominations']]=df[['Golden_Globe_Nominations']].apply(pd.to_numeric,errors='ignore')
df[['Bafta_Wins']]=df[['Bafta_Wins']].apply(pd.to_numeric,errors='ignore')
df[['Oscar_Wins']]=df[['Oscar_Wins']].apply(pd.to_numeric,errors='ignore')
df[['Prime_Wins']]=df[['Prime_Wins']].apply(pd.to_numeric,errors='ignore')
df[['Golden_Globe_Wins']]=df[['Golden_Globe_Wins']].apply(pd.to_numeric,errors='ignore')

#Adding nominations and wins of each award to actul total wins and nominations

df['Wins']=df['Wins'] + df['Bafta_Wins']+df['Oscar_Wins']+\
    df['Prime_Wins']+df['Golden_Globe_Wins']


df['Nominations']=df['Nominations']+df['Bafta_Nominations']+\
    df['Oscar_Nominations']+df['Prime_Nominations']+df['Golden_Globe_Nominations']

df.to_csv('Output\Question4.csv', sep=',', encoding='utf-8')

In [64]:
print(df.head(25))

,Title,Awards,Wins,Nominations,Bafta_Nominations,Oscar_Nominations,Prime_Nominations,Golden_Globe_Nominations,Bafta_Wins,Oscar_Wins,Prime_Wins,Golden_Globe_Wins
0,Book of Love: The Definitive Reason Why Men Ar...,NaN,0,0,0,0,0,0,0,0,0,0
1,Anderssons Ã¤lskarinna,NaN,0,0,0,0,0,0,0,0,0,0
2,Bad Blood,NaN,0,0,0,0,0,0,0,0,0,0
3,Who Are You?,1 win & 2 nominations.,1,2,0,0,0,0,0,0,0,0
4,Skeletons in the Closet,1 win.,1,0,0,0,0,0,0,0,0,0
5,Cheerleader Ninjas,1 nomination.,0,1,0,0,0,0,0,0,0,0
6,The Girl from Paris,3 wins & 2 nominations.,3,2,0,0,0,0,0,0,0,0
7,The Final Curtain,1 win & 1 nomination.,1,1,0,0,0,0,0,0,0,0
8,Crush,NaN,0,0,0,0,0,0,0,0,0,0
9,Happy Birthday,NaN,0,0,0,0,0,0,0,0,0,0
10,Run Like Hell,NaN,0,0,0,0,0,0,0,0,0,0
11,Crazy/Beautiful,5 nominations.,0,5,0,0,0,0,0,0,0,0
12,A Death in the Family,NaN,0,0,0,0,0,0,0,0,0,0
13,The Anniversary Party,2 wins & 5 nominations.,2,5,0,0,0,0,0,0,0,0
14,Life as We Know It,NaN,0,0,0,0,0,0,0,0,0,0
15,The Quiet American,Nominated for 1 Oscar. Another 13 wins & 13 no...,13,14,0,1,0,0,0,0,0,0
16,100 Centre Street,NaN,0,0,0,0,0,0,0,0,0,0
17,90-60-90,NaN,0,0,0,0,0,0,0,0,0,0
18,Like Cat and Mouse,5 wins & 4 nominations.,5,4,0,0,0,0,0,0,0,0
19,The Abduction Club,NaN,0,0,0,0,0,0,0,0,0,0
20,In Love and War,NaN,0,0,0,0,0,0,0,0,0,0
21,The Sign of Four,NaN,0,0,0,0,0,0,0,0,0,0
22,Adrian Mole: The Cappuccino Years,NaN,0,0,0,0,0,0,0,0,0,0
23,Amores querer con alevosÃ­a,NaN,0,0,0,0,0,0,0,0,0,0
24,Punch-Drunk Love,Nominated for 1 Golden Globe. Another 14 wins ...,14,35,0,0,0,1,0,0,0,0

In [47]:
df2 = df[['Awards']]

In [49]:
df3 = df2[df2['Awards'].isnull()==False]

In [50]:
df3

                                                  Awards
3                                 1 win & 2 nominations.
4                                                 1 win.
5                                          1 nomination.
6                                3 wins & 2 nominations.
7                                  1 win & 1 nomination.
11                                        5 nominations.
13                               2 wins & 5 nominations.
15     Nominated for 1 Oscar. Another 13 wins & 13 no...
18                               5 wins & 4 nominations.
24     Nominated for 1 Golden Globe. Another 14 wins ...
25                               3 wins & 2 nominations.
28                                         1 nomination.
31                                        5 nominations.
34                                1 win & 2 nominations.
37                             22 wins & 44 nominations.
38                                1 win & 3 nominations.
39                                1 win & 8 nominations.
43                                        2 nominations.
47                                6 wins & 1 nomination.
50     Won 2 Golden Globes. Another 68 wins & 201 nom...
51     Won 1 Golden Globe. Another 31 wins & 143 nomi...
53     Nominated for 4 Primetime Emmys. Another 16 no...
54                               3 wins & 2 nominations.
56                               3 wins & 6 nominations.
62                                               2 wins.
69                               6 wins & 4 nominations.
72                               7 wins & 6 nominations.
76                              9 wins & 30 nominations.
79     Won 1 Primetime Emmy. Another 1 win & 6 nomina...
84                                         1 nomination.
...                                                  ...
13668                                             1 win.
13669                                            5 wins.
13699                                             1 win.
13727                                     2 nominations.
13879                                      1 nomination.
13898                                      1 nomination.
13997                                             1 win.
14003                                      1 nomination.
14007                                             1 win.
14046                                      1 nomination.
14089                                     2 nominations.
14136                                      1 nomination.
14137                                     2 nominations.
14249                            2 wins & 2 nominations.
14346                                     2 nominations.
14432                            2 wins & 2 nominations.
14599                             2 wins & 1 nomination.
14652                                      1 nomination.
14761                                      1 nomination.
14792                                      1 nomination.
14800                                     2 nominations.
14805                                             1 win.
14873                                             1 win.
14908                                      1 nomination.
15177                                      1 nomination.
15180                                     2 nominations.
15219                                     2 nominations.
15230                                      1 nomination.
15234                              1 win & 1 nomination.
15269                                     7 nominations.

[1818 rows x 1 columns]

In [53]:
df3['Wins']=df3['Awards'].apply(lambda x: (re.findall(r"(\d+) win",x)))
df3['Wins']=df3['Wins'].apply(lambda x:[0] if len(x)==0 else x)

C:\Users\vs\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
C:\Users\vs\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

In [60]:
df3['Wins']=df3['Wins'].apply([lambda x: x.replace('[]',''))

TypeError: 'list' object is not callable

In [ ]:
df3['wins']=df3['Awards'].apply(lambda x: list(map(int,x))[0])

In [43]:
df2['Awards'].str.extract('([wins])', expand=True)

         0
0      NaN
1      NaN
2      NaN
3        w
4        w
5        n
6        w
7        w
8      NaN
9      NaN
10     NaN
11       n
12     NaN
13       w
14     NaN
15       i
16     NaN
17     NaN
18       w
19     NaN
20     NaN
21     NaN
22     NaN
23     NaN
24       i
25       w
26     NaN
27     NaN
28       n
29     NaN
...    ...
15357  NaN
15358  NaN
15359  NaN
15360  NaN
15361  NaN
15362  NaN
15363  NaN
15364  NaN
15365  NaN
15366  NaN
15367  NaN
15368  NaN
15369  NaN
15370  NaN
15371  NaN
15372  NaN
15373  NaN
15374  NaN
15375  NaN
15376  NaN
15377  NaN
15378  NaN
15379  NaN
15380  NaN
15381  NaN
15382  NaN
15383  NaN
15384  NaN
15385  NaN
15386  NaN

[15387 rows x 1 columns]

In [35]:
df2['Awards'].str.extract(['(win)(/d)'])

C:\Users\vs\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
  if __name__ == '__main__':

TypeError: unhashable type: 'list'